#! /bin/bash

#PBS -N question8
#PBS -q tiny12core
#PBS -j oe
#PBS -m abe
#PBS -M rwretnan@uark.edu
#PBS -o rwretnan_assn04.8.3.out
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:00:30:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+

makeblastdb -in watermelon.fsa -dbtype nucl

blastn -outfmt 0 -dust yes -word_size 7 -reward 5 -penalty -4 -gapopen 8 -gapextend 6 -query watermelon.fsa -db watermelon.fsa

