#! /bin/bash

#PBS -N question4
#PBS -q tiny12core
#PBS -j oe
#PBS -m abe
#PBS -M rwretnan@uark.edu
#PBS -o rwretnan_assn04.4.out
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:00:10:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+
cd /home/rwretnan/test_directory/watermelon_files/mt_genomes
cat *.fasta | makeblastdb  -dbtype nucl -title newdb

blastn -query /home/rwretnan/test_directory/watermelon_files/watermelon_nt/nad4L.fasta -db newdb

