#! /bin/bash

#PBS -N question3
#PBS -q tiny12core
#PBS -j oe
#PBS -m abe
#PBS -M rwretnan@uark.edu
#PBS -o rwretnan_assn04.3.out
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:00:10:00

cd $PBS_O_WORKDIR

module load blast/2.6.0+

cd /home/rwretnan/test_directory/watermelon_files/watermelon.fsa -dbtype nucl
makeblastdb -in nad4L.fasta -dbtype nucl -out watermelon.fsa

blastn -query nad4L.fasta -db watermelon.fsa
